import sqlite3

conn = sqlite3.connect('stories.db')
c = conn.cursor()

c.execute('''
CREATE TABLE IF NOT EXISTS stories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    image TEXT
)
''')

c.execute('''
CREATE TABLE IF NOT EXISTS steps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    story_id INTEGER NOT NULL,
    step_number INTEGER NOT NULL,
    content TEXT NOT NULL,
    option1 TEXT,
    option2 TEXT,
    next1 INTEGER,
    next2 INTEGER,
    FOREIGN KEY(story_id) REFERENCES stories(id)
)
''')

stories = [
    ('Don’t Bully Me 🚫', 'child_right.jpg', [
        (1, 'You’re in school. A group of kids are bullying a quiet student in the corner. They’re laughing at his clothes and calling him names.', 'Join them 😬', 'Stand up for the student ❌', 2, 3),
        (2, 'You laugh along. The bullied student looks down, almost in tears. A teacher sees you from afar.', 'Run away quickly', 'Act innocent', 4, 5),
        (3, 'You take a deep breath and step forward. “That’s not funny,” you say. The bullies pause.', 'Challenge them loudly 😤', 'Get help from a teacher or senior 💡', 6, 7),
        (4, 'You try to run, but the teacher calls your name. You’re caught and taken to the principal’s office. You feel scared.', 'Say sorry and explain', 'Blame the others', 8, 9),
        (5, 'You act innocent, but the teacher saw everything. You’re warned and sent home with a note. The bullied student still sits alone.', None, None, None, None),
        (6, 'You yell, “Leave him alone!” but they laugh at you too. One pushes you slightly. It’s getting tense.', 'Push back', 'Call a teacher loudly', 10, 11),
        (7, 'You rush to a nearby teacher and say, “They’re bullying him!” The teacher comes quickly and stops it. The quiet student looks relieved.', 'Go sit beside the student', 'Walk away quietly', 12, 13),
        (8, 'You say sorry and tell the truth. The principal explains why bullying is hurtful. You feel guilty, but it helps you change.', 'Apologize to the student', 'Stay silent', 14, 15),
        (9, 'You blame others, but the principal doesn’t believe you. You’re suspended for 2 days. You feel ashamed.', None, None, None, None),
        (10, 'You push back and a fight begins. Both of you get taken to the office. Even though you were trying to help, violence wasn’t the answer.', None, None, None, None),
        (11, 'You shout, “Teacher! Help!” and an adult comes immediately. The bullies back off. You feel nervous but strong.', 'Check on the student', 'Just walk away', 12, 13),
        (12, 'You sit beside the bullied student and say, “You okay?” He nods and whispers, “Thanks.” You smile.', 'Offer to eat lunch together 🍱', 'Say “Let’s be friends” 💬', 16, 17),
        (13, 'You walk away. The student is safe now, but maybe they still feel alone.', None, None, None, None),
        (14, 'You say sorry to the student. He looks surprised, but nods slowly. You decide to never bully again.', None, None, None, None),
        (15, 'You don’t say anything. You know what you did. Maybe next time you’ll do better.', None, None, None, None),
        (16, 'You two sit under a tree and eat quietly. For the first time, he smiles a little. Maybe you made a new friend today 🌳', None, None, None, None),
        (17, 'You say, “Let’s be friends.” He whispers, “I’d like that.” You just made someone feel seen. And that’s powerful 💙', None, None, None, None),
    ]),
    ('Pink Football Shoes 👟', 'football_girl.jpg', [
        (1, 'You’re a 13-year-old girl who loves football. One day, you wear your new pink football shoes to school and join the boys playing during lunch break.', 'Ask to join the game', 'Just watch from far', 2, 3),
        (2, 'You ask to play. The boys laugh. “Football is not for girls,” one says. But one boy, Shivaan, says, “Why not? Let her play.”',  'Join confidently', 'Run away embarrassed', 4, 5),
        (3, 'You just watch. Inside, your heart aches. Why can’t you just play like everyone else?', None, None, None, None),
        (4, 'You start playing and surprise everyone with your speed. Shivaan passes the ball to you — you score a goal!', 'Celebrate shyly', 'Show confidence', 6, 7), 
        (5, 'You run away. Everyone forgets it soon, but you don’t. You start hiding your love for football. 💔', None, None, None, None),
        (6, 'You blush and smile. Shivaan comes to you and says, “You were amazing out there.”', 'Say thank you and walk away', 'Tell him you want to join practice regularly', 8, 9),
        (7, 'You raise your hand in the air, smiling wide. Some kids cheer, some boys whisper, “Show off.”', 'Ignore the whispers', 'Get nervous and step back', 10, 11),
        (8, 'You thank him and leave. But the next day, you notice Shivaan being teased for supporting a girl.', 'Talk to him', 'Avoid him to protect him', 12, 13),
        (9, 'He grins. “Then meet us at practice tomorrow morning!” Your heart skips a beat.', 'Tell your parents you’re joining', 'Sneak out for practice', 14, 15),
        (10, 'You ignore the whispers and play harder. You fall, get bruised, but get up and keep going.', 'Tell your teacher about the comments', 'Let your game speak', 16, 17),
        (11, 'You feel small again and step back. Shivaan looks confused. “You okay?” he asks softly.', 'Tell him the truth', 'Say you’re fine and leave', 18, 19),
        (12, 'You talk to Shivaan. He says, “Let them say what they want. I know you deserve to play.”', 'Thank him and play again', 'Tell him to stop supporting you', 20, 21),
        (13, 'You avoid him. He looks hurt. The support you had slowly disappears.', None, None, None, None),
        (14, 'Your parents are shocked. “Football? But it’s rough. It’s for boys.”', 'Explain calmly why you love it', 'Shout at them emotionally', 22, 23),
        (15, 'You sneak out, but one day your mom finds out. She’s furious.', 'Apologize and explain', 'Get into a big fight', 24, 25),
        (16, 'You tell your teacher. She listens and gives a long lecture to the class about gender equality. You feel proud.', 'Start a girls football group', 'Thank her silently', 26, 27),
        (17, 'You let your game speak. Slowly, the teasing stops. People respect your skill.', 'Join the school football team', 'Help another shy girl join too', 28, 29),
        (18, 'You tell him how people’s words hurt. “Then let’s prove them wrong,” he says.', 'Train hard with him', 'Ask teacher to help', 30, 31),
        (19, 'You hide your pain. Shivaan feels something’s off. Slowly, he starts drifting.', None, None, None, None),
        (20, 'You play again with full energy. More girls join in. The field feels alive.', 'Start teaching younger girls too', 'Design your own football jersey', 32, 33),
        (21, 'You tell him to stop. “I was just trying to be a friend,” he says quietly. You feel a pang of regret.', None, None, None, None),
        (22, 'You tell your parents, “I feel strong when I play. I feel free.” They listen silently.', 'Show them your medals', 'Invite them to your match', 34, 35),
        (23, 'You shout, and things get worse. “You’re turning wild!” your father says. It hurts.', 'Calm down and try again', 'Leave the house crying', 36, 37),
        (24, 'You apologize and explain. Mom slowly softens. “If it makes you happy, try… but safely.”','Hug her and thank her', 'Ask her to come to your match', 38, 39),
        (25, 'You both scream and cry. The next day, she gives you silent treatment.', None, None, None, None),
        (26, 'You start a girls football club. Soon, 5 more girls join. One says, “I was scared, but you inspired me.”','Print team jerseys', 'Name your team “Power Girls”', 40, 41),
        (27, 'You thank your teacher with teary eyes. She hugs you. “Keep breaking walls,” she says.', None, None, None, None),
        (28, 'You officially join the school football team. You become the *first girl captain* in school history!', 'Plan a school event on equality', 'Make a speech in assembly', 42, 43),
        (29, 'You help a shy girl named Meera to play. “I never thought I could,” she says. You smile.', 'Train with her daily', 'Tell her she’s powerful', 44, 45),
        (30, 'You train with Shivaan. People stare, but your game gets sharper each day.', 'Win interschool tryouts', 'Lead by example', 46, 47),
        (31, 'Your teacher helps you create a gender-equality campaign. Posters go up all over school.', 'Speak in a panel discussion', 'Make an awareness video', 48, 49),
        (32, 'You train younger girls. They look up to you. “I want to be like you one day!” one says.', None, None, None, None),
        (33, 'You design a jersey that says “Girls Can Too.” Everyone starts asking where to buy it!', None, None, None, None),
        (34, 'You show your medals and certificates. Your dad silently nods and says, “I’m proud.”', None, None, None, None),
        (35, 'Your parents come and watch your match. You win. Your mom claps with tears in her eyes.', None, None, None, None),
        (36, 'You calm down and talk again. This time, your dad listens. He says, “Try… just don’t get hurt.”', None, None, None, None),
        (37, 'You run out crying. It feels like your dreams are crumbling. You sit alone on the stairs.', None, None, None, None),
        (38, 'You hug her tight. “Thank you for believing in me,” you whisper.', None, None, None, None),
        (39, 'You invite her. She cheers the loudest. You wave from the ground. She waves back proudly.', None, None, None, None),
        (40, 'You print jerseys and your team wins the friendly match. Local news features your story!', None, None, None, None),
        (41, 'You name the team “Power Girls.” The principal smiles and says, “That name fits perfectly.”', None, None, None, None),
        (42, 'You organize “Girls in Sports” day at school. Many kids say, “I didn’t know girls could play *this* good!”', None, None, None, None),
        (43, 'You give a speech: “Courage doesn’t wear a jersey number. It wears a heart.” Standing ovation.', None, None, None, None),
        (44, 'You and Meera train daily. One day, she scores a goal and hugs you tight.', None, None, None, None),
        (45, 'You tell her she’s powerful. “No one ever said that to me,” she says, teary-eyed.', None, None, None, None),
        (46, 'You win interschool trials and get selected to represent your district!', None, None, None, None),
        (47, 'Without arguing, you keep playing. Soon, no one questions your place on the field.', None, None, None, None),
        (48, 'You speak at a district event. “It’s time we let *everyone* dream freely,” you say. Loud applause.', None, None, None, None),
        (49, 'You make a short film called “Let Her Play.” It gets 10k views and inspires many!', None, None, None, None),
    ]),
    ('Boy at the Tea Stall 🫖', 'tea_stall.jpg', [
        (1, 'You’re in 7th grade, walking home from school. You see a boy, around your age, washing glasses at a tea stall. He looks tired, dirty, and sweaty.','Ignore and walk home', 'Buy tea and ask about him', 2, 3),
        (2, 'You walk away, thinking it’s none of your business. But at night, you feel guilty. You wish you had done something. 😞', None, None, None, None),
        (3, 'You gently ask his name. “Aman,” he says. You ask if he goes to school. He shrugs and says, “Not anymore.”','Ask why he stopped school', 'Just nod and walk away', 4, 5),
        (4, 'He says his father passed away, and he works to support his mother. “I loved school,” he whispers.','Offer to help him study', 'Tell your teacher about him', 6, 7),
        (5, 'You walk away after talking. Aman’s sad face stays in your mind all evening. You wonder if anyone will ever help him.', None, None, None, None),
        (6, 'You visit him every day after school and start teaching him. He learns fast. You become good friends.', 'Gift him a book', 'Keep teaching daily', 8, 9),
        (7, 'Your teacher listens carefully and says, “Let me talk to the principal and Childline.”', 'Help them meet Aman', 'Stay back and let them handle', 10, 11),
        (8, 'You gift him your old English book. He hugs it tightly. “Thank you,” he says. His eyes shine.', 'Ask your parents to help him', 'Encourage him to never give up', 12, 13),
        (9, 'You keep teaching him, and he tells you, “You’re the best teacher I ever had.” You feel proud.', 'Ask your teacher for more help', 'Help him apply to night school', 14, 15),
        (10, 'You help the teacher meet Aman. The school arranges an NGO visit. Aman is nervous but hopeful.', 'Support him through the process', 'Step back and watch', 16, 17),
        (11, 'You let them handle it, but Aman misses your support. He becomes scared and refuses to meet the NGO.', None, None, None, None),
        (12, 'Your parents talk to Aman’s mother. They help her apply for government schemes. Aman may get to study again!', 'Celebrate with Aman', 'Stay humble and keep helping', 18, 19),
        (13, 'Aman starts to believe in himself. He says, “One day, I’ll be like you — wearing a uniform and going to school.”', 'Promise to always support him', 'Tell him to dream big', 20, 21),
        (14, 'The teacher says there’s a night school nearby. You help Aman apply. He starts attending classes!', 'Celebrate with a treat', 'Keep checking on his progress', 22, 23),
        (15, 'You go with Aman to register. He feels nervous but happy. You promise to always help.', 'Ask others to help too', 'Buy him a school bag', 24, 25),
        (16, 'The NGO arranges for Aman to join a government support program. His life begins to change.', 'Stay friends and help him adjust', 'Encourage him to speak at school', 26, 27),
        (17, 'Without your support, Aman struggles to adjust to the new system. He eventually stops going.', None, None, None, None),
        (18, 'You and Aman share sweets and laugh together. “I’ll never forget you,” he says.', 'Plan to help more kids', 'Write about Aman’s story', 28, 29),
        (19, 'You keep helping silently. Aman improves each day. You feel proud but never boast.', 'Help more kids at the stall', 'Start a small awareness group', 28, 29),
        (20, 'You promise him your support. Aman tears up and smiles. “You’re my best friend.”', 'Keep being there for him', 'Help him write his dreams on paper', 30, 31),
        (21, 'You tell him to dream big. Aman writes: “I will become a teacher one day.”', 'Help him start a goal book', 'Make a study plan for him', 32, 33),
        (22, 'You buy samosas and both sit and laugh like old friends. “You’re the reason I’m studying again,” Aman says.', 'Write your experience in school magazine', 'Organize a school talk', 34, 35),
        (23, 'You regularly visit his night school. The teacher thanks you. Aman is now a top student.','Ask your principal to reward him', 'Help him prepare for exams', 36, 37),
        (24, 'Others join you and help kids like Aman. A little kindness spreads far.', None, None, None, None),
        (25, 'You gift him a school bag. “My first school bag!” he beams. He hugs it tightly.', 'Encourage him to share his story', 'Take a photo to remember', 38, 39),
        (26, 'Aman adjusts well, and even inspires other children to join school. He becomes a role model.', 'Nominate him for a school award', 'Help him give a speech in assembly', 40, 41),
        (27, 'Aman struggles a bit, but with your help, he settles in. The NGO gives him free books and food.', 'Help others join too', 'Create posters about child rights', 42, 43),
        (28, 'Your story gets printed in the school magazine. Many students get inspired to help.', None, None, None, None),
        (29, 'You start a small team with friends to help other children in need. Your teacher praises your effort.', None, None, None, None),
        (30, 'You stay by Aman’s side like a true friend. He never gives up on studies again.', None, None, None, None),
        (31, 'He draws a small photo of his dream school and sticks it on the wall. Every day, he looks at it.', None, None, None, None),
        (32, 'You help him start a “dream diary.” His first entry says: “I will become a good man.”', None, None, None, None),
        (33, 'You make him a weekly plan. “You’re my coach now,” he says with a grin.', None, None, None, None),
        (34, 'Your experience inspires a full school campaign. You name it: “Each One, Teach One.”', None, None, None, None),
        (35, 'Your speech at school brings awareness. Some kids even start donating their old books!', None, None, None, None),
        (36, 'Your principal gives Aman a certificate of courage. Everyone claps. He bows with pride.', None, None, None, None),
        (37, 'You sit with him and prepare for his night school exams. “One day, I’ll help other Aamans,” he says.', None, None, None, None),
        (38, 'His story goes viral after your teacher posts about it. NGOs across the city start supporting similar kids.', None, None, None, None),
        (39, 'You frame the photo and keep it in your room. A daily reminder that you made a difference.', None, None, None, None),
        (40, 'He wins the award and gives a small speech: “This is for the girl who believed in me.” 💖', None, None, None, None),
        (41, 'His assembly speech moves everyone to tears. He gets a standing ovation. You cry too.', None, None, None, None),
        (42, 'Your school starts a club to support underprivileged children. You become its founder.', None, None, None, None),
        (43, 'Your posters get displayed across town. People appreciate your efforts to raise awareness.', None, None, None, None),
    ]),
    ('The Empty Bench 🌳', 'bench_girl.jpg', [
        (1, 'You’re an average student. Not popular, not invisible. But lately, a group of girls in class tease you for your “boring” clothes and introvert nature. At lunch, you sit alone on a bench near the garden.', 'Cry quietly', 'Open your sketchbook and draw', 2, 3),
        (2, 'Tears fall, but you quickly wipe them away as someone walks by. It’s Riya, the class topper. She gives you a small smile but doesn’t stop.', 'Ignore her', 'Smile back softly', 4, 5),
        (3, 'You begin to sketch a tree — calm, grounded, silent. It makes you feel better inside.', 'Write a quote below it', 'Color it fully', 6, 7),
        (4, 'You ignore her and stay silent. Another lonely day passes. The bullies win — again.', None, None, None, None),
        (5, 'Riya notices and walks over. “You draw beautifully,” she says, pointing to your sketchbook.', 'Feel shy but say thank you', 'Close the sketchbook nervously', 8, 9),
        (6, 'You write: “Be strong like trees — they grow silently.” You feel a spark of strength.', 'Post it on the class board', 'Keep it to yourself', 10, 11),
        (7, 'The colors brighten your mood. The empty bench doesn’t feel so lonely anymore.', 'Draw every lunch break', 'Give the sketch to a classmate', 12, 13),
        (8, 'She smiles and sits beside you. “I sit alone too sometimes. People expect me to be perfect.”', 'Open up about your pain', 'Change the topic', 14, 15),
        (9, 'You close the sketchbook nervously. Riya nods gently. “You don’t need to hide your light.”', 'Ask her to stay', 'Let her walk away', 16, 17),
        (10, 'You post your sketch on the notice board. Next day, you see *two more* sketches by unknown students with quotes.', 'Start a “Sketch & Smile” club', 'Feel quietly proud', 18, 19),
        (11, 'You keep it. Later that night, you read it again. It feels like a hug from yourself.', None, None, None, None),
        (12, 'You sketch daily. One day, a junior girl comes to you and says, “Your drawings inspire me.”', 'Offer to teach her', 'Just thank her', 20, 21),
        (13, 'You give the sketch to the girl who’s usually rude to you. She stares at it, says nothing… but the teasing stops after that.', None, None, None, None),
        (14, 'You share your story. Riya listens with full attention. “You’re stronger than you think,” she says.', 'Decide to stop hiding', 'Ask her to sit with you daily', 22, 23),
        (15, 'You talk about books instead. The two of you slowly bond over shared interests.', 'Exchange books weekly', 'Start a mini book club', 24, 25),
        (16, 'You ask, “Can you stay for a while?” She smiles. “Of course.” For the first time, the bench feels like home.', None, None, None, None),
        (17, 'She walks away, but that one moment gave you courage to face the next day.', None, None, None, None),
        (18, 'You start the club. More students join. The class feels lighter. Even the bullies start drawing.', None, None, None, None),
        (19, 'You smile silently. Some victories don’t need applause — just peace.', None, None, None, None),
        (20, 'You teach her after school. Soon, others join. You become someone people look up to.', None, None, None, None),
        (21, 'You thank her. But later, you wonder: maybe you *are* inspiring. Quietly.', None, None, None, None),
        (22, 'You stop hiding your talents. You write poems, sketch, speak up. Slowly, people notice.', None, None, None, None),
        (23, 'You and Riya eat together daily. The bench becomes a symbol of friendship and quiet strength.', None, None, None, None),
        (24, 'You start a book exchange. Soon, classmates join. The class grows more connected.', None, None, None, None),
        (25, 'The book club flourishes. Even the bullies ask to borrow books. Something shifts.', None, None, None, None),
    ]),
    ('The Torn Notebook 📒', 'bully_notebook.jpg', [
        (1, 'A new student named Anvi joins your class. She wears old clothes, speaks less, and always sits in the last bench. One day during break, some kids tear her notebook and laugh.','Laugh with them', 'Tell them to stop', 2, 3),
        (2, 'You laugh nervously, trying to fit in. But Anvi sees you. Her eyes fill with tears. She quietly picks up the torn pages.', 'Feel guilty but do nothing', 'Go and help her later', 4, 5),
        (3, 'You shout, “This isn’t funny!” The bullies roll their eyes and walk away. Anvi looks at you, surprised but thankful.', 'Sit beside her', 'Walk away silently', 6, 7),
        (4, 'You avoid her. But you can’t forget her sad face. You feel uneasy all day.', 'Apologize the next day', 'Ignore it', 8, 9),
        (5, 'You help Anvi gather the pages. She says softly, “Thank you.”', 'Smile and talk to her', 'Just nod and leave', 10, 11),
        (6, 'You sit beside her. She’s shy, but slowly opens up. You learn she had to leave her old school because of financial issues.', 'Offer to share books', 'Just listen quietly', 12, 13),
        (7, 'You walk away. Next day, you see her sitting even more quietly than before. Guilt creeps in.', 'Write her an anonymous letter of support', 'Ignore and move on', 14, 15),
        (8, 'You say sorry. She nods slowly. “It’s okay,” she says. But the damage still lingers.', 'Make it right by being kind now', 'Just move on', 16, 17),
        (9, 'You ignore it. But inside, you know you became someone you didn’t want to be.', None, None, None, None),
        (10, 'She smiles. “You’re the first person who talked to me,” she says. You feel proud.', 'Introduce her to others', 'Sit with her daily', 18, 19),
        (11, 'You nod and leave. Later, you regret not saying more.', None, None, None, None),
        (12, 'You offer to share books and notes. Anvi is so happy she almost tears up. “No one has ever been this kind,” she says.', 'Start studying together', 'Ask her to help you too', 20, 21),
        (13, 'You listen quietly. She opens up more. You realize she’s very talented in drawing.', 'Encourage her to participate in art contest', 'Ask her to show you sketches', 22, 23),
        (14, 'She finds the letter in her desk. Her eyes widen. She clutches it and smiles. That day, she doesn’t sit alone.', 'Reveal you wrote it', 'Keep it a secret', 24, 25),
        (15, 'You ignore it. Later in life, you remember that bench, that torn notebook... and wonder if you could’ve done better.', None, None, None, None),
        (16, 'You bring her extra pencils and talk kindly. Slowly, you earn back her trust.', None, None, None, None),
        (17, 'You move on. But the story remains unfinished in your heart.', None, None, None, None),
        (18, 'You introduce her to your group. At first, they’re unsure, but she slowly becomes one of them.', 'Stand up if someone mocks her', 'Stay silent when others whisper', 26, 27),
        (19, 'You sit with her daily. She starts smiling more. You both become great friends.', None, None, None, None),
        (20, 'You both study together and score well. She blossoms with confidence.', None, None, None, None),
        (21, 'She feels respected, like an equal. It changes her world.', None, None, None, None),
        (22, 'You tell the art teacher about her. Anvi wins first prize in the annual contest!', None, None, None, None),
        (23, 'She shows you her sketches — drawings of her dreams, pain, and hope. You realize how strong she is.', None, None, None, None),
        (24, 'You tell her it was you. She hugs you. “You saved me without even being near,” she whispers.', None, None, None, None),
        (25, 'You stay quiet. But every time you pass her, she smiles. That’s enough for you.', None, None, None, None),
        (26, 'Someone mocks her new shoes. You stand up. “Stop judging people by what they wear.” Everyone goes quiet.', None, None, None, None),
        (27, 'You stay silent. Anvi looks at you, hurt. Your silence feels like betrayal.', None, None, None, None),
    ]),
    ('The Invisible Stage 🎤', 'stage_fear.jpg', [
        (1, 'You love singing, but you’ve never performed in front of people. Your school announces a talent show. Your best friend signs you up without telling you!', 'Get angry and quit', 'Give it a try', 2, 3),
        (2, 'You cancel your name. Your friend feels bad, “You always sing so beautifully at home…”', 'Apologize and explain your fear', 'Ignore and walk away', 4, 5),
        (3, 'You panic but agree. Every night, you practice softly in your room, hands shaking.', 'Ask your teacher for help', 'Hide and practice alone', 6, 7),
        (4, 'You tell your friend, “I get so nervous on stage.” They nod, “I believe in you, but I’ll support whatever you decide.”', 'Think about trying again', 'Stick to your decision', 8, 9),
        (5, 'You walk away. On the day of the show, you clap for others and silently wish you had tried.', None, None, None, None),
        (6, 'Your teacher helps you with breathing techniques and confidence. You feel a little stronger.', 'Perform on the stage', 'Back out last minute', 10, 11),
        (7, 'You practice alone, but the fear still grips you. You doubt if you can do this.', 'Talk to your friend', 'Try meditating', 12, 13),
        (8, 'You decide to give it a shot after all. You ask if your friend can sing beside you for support.', 'Perform together', 'Sing solo with friend backstage', 14, 15),
        (9, 'You stick to your decision. But every time you hum to yourself, you wonder what could’ve been.', None, None, None, None),
        (10, 'Your hands tremble as you walk on stage. Lights blind you. But when the music starts… you sing.',  'Look at a friendly face in the crowd', 'Close your eyes and sing from the heart', 16, 17),
        (11, 'You back out. Your teacher smiles kindly, “Maybe next time. You still grew stronger.”', None, None, None, None),
        (12, 'Your friend says, “Even if you mess up, I’ll clap the loudest.” You smile.', 'Perform with courage', 'Let someone else sing your song', 18, 19),
        (13, 'You meditate every night. Slowly, your mind calms. You feel something shift within.', 'Face the stage', 'Stay off-stage but help others', 20, 21),
        (14, 'You both perform together. The hall erupts in cheers. You smile brightly — your first step.', None, None, None, None),
        (15, 'You sing solo. Your voice cracks at first, but you keep going. You finish strong. The applause echoes in your ears.', None, None, None, None),
        (16, 'You spot your friend in the crowd, beaming. That gives you all the strength you need.', None, None, None, None),
        (17, 'You close your eyes and lose yourself in the music. When you finish, the whole auditorium is silent… and then applause bursts out.', None, None, None, None),
        (18, 'You go on stage. Your friend claps loudly for you. You sing, not perfectly — but *bravely*.', None, None, None, None),
        (19, 'Someone else sings your song. You smile watching them, but your heart whispers — “I wish it was me.”', None, None, None, None),
        (20, 'You stand on stage, your fear melting into courage. You own the moment. You win — not a prize, but yourself.', None, None, None, None),
        (21, 'You stay backstage and help others prepare. Everyone thanks you. You realize, even offstage, you made an impact.', None, None, None, None),
    ]),
    ('The School Gate 🚪', 'school_rights.jpg', [
        (1, 'You’re a 12-year-old boy named Shivay. You live in a small town. Every morning, you see other kids in uniforms going to school. But your parents say, “We can’t afford school for you.”', 'Stay silent and help your father in work', 'Ask your parents again about school', 2, 3),
        (2, 'You begin working at a tea stall with your father. You dream of sitting in a classroom one day, but never say anything.', 'Forget about school', 'Still hope silently', 4, 5),
        (3, 'Your parents sigh, “We wish we could… but uniforms, books, fees… it’s all too much.”', 'Give up', 'Talk to your neighbor uncle who’s a teacher', 6, 7),
        (4, 'You forget your dreams. Years pass. One day, you see a boy your age becoming a police officer. You wonder, “What if…?”', None, None, None, None),
        (5, 'You keep dreaming. One day, you secretly follow some students and watch them study through the window.', 'Feel inspired and leave', 'Keep watching daily', 8, 9),
        (6, 'You give up. Life moves on. You become part of a cycle many children fall into — child labor and lost potential.', None, None, None, None),
        (7, 'You go to your neighbor, Mr. Singh. He listens and says, “Beta, every child in India has a **legal right to free education till age 14**. It’s the law.”', 'Ask how to join school', 'Feel it’s impossible', 10, 11),
        (8, 'You leave, but that fire in your heart is still alive.','Try talking to someone about your dream', 'Start reading thrown-away books', 12, 13),
        (9, 'You watch every day. A teacher inside notices you. One day, she comes out and says, “Do you want to study?”', 'Nod yes with tears', 'Run away shyly', 14, 15),
        (10, 'Mr. Singh takes you to a government school. The principal says, “Yes, he can join. No fees. No books cost. It’s his **legal right.**”', 'Feel shocked and grateful', 'Hesitate and feel small', 16, 17),
        (11, 'You feel small and walk away. But deep inside, something tells you not to give up.', 'Go back to Mr. Singh', 'Try studying on your own', 18, 19),
        (12, 'You tell the lady who sweeps your street. She says, “My daughter studies in govt school. It’s free.”', 'Go there next day', 'Ignore it', 20, 21),
        (13, 'You pick up books thrown outside. You start reading every night. Slowly, you begin to learn.', 'Dream of school again', 'Stay silent', 22, 23),
        (14, 'You nod with teary eyes. The teacher smiles, holds your hand, and says, “You’re coming in tomorrow.”', None, None, None, None),
        (15, 'You run away shyly. But the next day, you return and she smiles at you again. You’re brave.', 'Say “I want to learn”', 'Stay silent', 14, 23),
        (16, 'You join school. You wear a borrowed uniform. You sit on a bench for the first time, holding a real book. You feel proud.', None, None, None, None),
        (17, 'You hesitate. The principal bends down and says, “You are just like my son. You belong here.”', 'Smile and join', 'Still unsure', 16, 23),
        (18, 'You return to Mr. Singh. This time, he walks with you to school and fights for your right.', 'Join happily', 'Cry with joy', 16, 16),
        (19, 'You try learning on your own. But you know in your heart, you need a classroom.', 'Build courage to ask again', 'Stay in shadows', 10, 24),
        (20, 'You walk to the school gate. The teacher at the entrance smiles, “Come in, child. Everyone belongs here.”', None, None, None, None),
        (21, 'You ignore it. But that same night, you dream of sitting on a school bench. The desire never leaves.', None, None, None, None),
        (22, 'You dream of learning, becoming someone big. You promise yourself — one day, you’ll get in.', None, None, None, None),
        (23, 'You stay silent, but the world doesn’t. One day, someone stands up for you.', 'Accept the help', 'Say “I’ll do it myself”', 16, 13),
        (24, 'You remain in shadows. Your talent remains hidden. But your heart always knew you deserved more.', None, None, None, None),
    ]),
    ('No More Secrets 🔒', 'protection_abuse.jpg', [
        (1, 'You’re a 10-year-old girl named Prinjal. Every evening, your mom goes to work and leaves you with a relative. He always smiles—but lately, something feels weird. He touches you in ways that make you uncomfortable.', 'Stay silent and avoid him', 'Tell your mom', 2, 3),
        (2, 'You try to avoid him, but he keeps finding ways to be near you. The fear grows.', 'Try to hide your feelings', 'Tell your teacher', 4, 5),
        (3, 'You gather courage and tell your mom. She goes quiet, then hugs you tight and says, “You were very brave to tell me.”', 'Feel safe and cry', 'Ask what will happen now', 6, 7),
        (4, 'You hide your feelings, but the fear starts affecting your studies, your sleep, your smile.', 'Keep hiding', 'Try again to tell someone', 8, 5),
        (5, 'You whisper to your teacher, “I feel scared when uncle is around me.” The teacher listens calmly and says, “Thank you for trusting me.”','Feel relieved', 'Get nervous', 9, 10),
        (6, 'Your mom takes you to a Child Protection Officer. They speak kindly, and tell you what happened was **not your fault at all.**', 'Listen quietly', 'Ask questions', 11, 12),
        (7, 'Your mom explains, “In India, there is a law called POCSO. No one has the right to hurt or touch a child in an unsafe way. You are protected by law.”', 'Feel empowered', 'Still feel scared', 13, 14),
        (8, 'You keep hiding. But one day, you burst into tears in class. Your teacher understands something is wrong.', 'Open up to her', 'Run away from the room', 5, 15),
        (9, 'You feel like a weight has been lifted. You finally feel heard.','Share more', 'Stay silent now', 11, 16),
        (10, 'You get nervous, but the teacher assures, “You did the right thing. You’re not alone now.”', 'Cry and hug her', 'Nod silently', 11, 16),
        (11, 'You’re taken to a counselor who helps you talk and heal. Slowly, you begin to feel safer again.', 'Talk about feelings', 'Just listen for now', 17, 18),
        (12, 'You ask, “Will I be okay again?” The officer smiles gently and says, “Yes, very soon. You’re already stronger than you think.”', 'Smile bravely', 'Stay quiet', 17, 18),
        (13, 'You learn about **“safe touch” and “unsafe touch.”** Your teacher gives you a booklet and says, “Every child must know their body belongs only to them.”', 'Read it with interest', 'Share with a friend', 19, 20),
        (14, 'You’re still scared, but you’re not alone anymore. You know there are people who will protect you.', 'Trust again slowly', 'Stay cautious', 19, 18),
        (15, 'You run away, but the teacher finds you gently and says, “You don’t have to run. We will always protect you.”', 'Finally talk', 'Just cry', 11, 18),
        (16, 'You stay silent, but now you know someone is watching out for you.', 'Begin healing', 'Stay distant', 17, 18),
        (17, 'Months later, you speak at a school event about child rights. You say, “I thought I was weak, but I became strong when I spoke up.” 🕊️', None, None, None, None),
        (18, 'You take time, but healing begins. You draw, write, and smile more than before.', None, None, None, None),
        (19, 'You read about the **Childline 1098 number** and learn that help is just a call away if any child feels unsafe.', 'Remember it forever', 'Share it in class', 17, 20),
        (20, 'You share the booklet with friends. Now they know too—**“No one has the right to hurt us.”**', 'Smile and feel proud', 'Tell your teacher too', 17, 17),
    ]),
    ('Respect My Space ✋', 'my_body.jpg', [
        (1, 'You are 9 years old and your teacher gives a lesson on “Good Touch and Bad Touch.” What do you feel?', 'Curious to know more', 'Too shy to listen', 2, 3),
        (2, 'That’s great! Understanding your body and rights is very important.', 'Pay full attention to the lesson', 'Giggle with your friend', 4, 5),
        (3, 'It’s okay to feel shy, but this lesson is very important for your safety. Let’s give it a try. 😊', 'Try to understand the topic', 'Keep ignoring', 2, 6),
        (4, 'The teacher says: “Good touches make you feel safe, loved, and cared for — like hugs from family.”', 'Nod and smile', 'Feel confused', 7, 8),
        (5, 'You giggle and miss an important part of the lesson. The teacher asks if you’re taking it seriously.', 'Apologize and listen', 'Keep laughing', 4, 6),
        (6, 'Ignoring such topics might leave you unaware of your rights. It’s always good to learn.', None, None, None, None),
        (7, 'Then the teacher explains: “Bad touches make you feel scared, uncomfortable, or confused. No one should touch your private parts.”', 'Raise hand and ask questions', 'Stay quiet but understand', 9, 10),
        (8, 'Confusion is normal. You raise your hand and ask the teacher to explain again.', 'Ask about safe and unsafe secrets', 'Wait silently', 9, 10),
        (9, 'The teacher says: “Good secrets are about surprises. Bad secrets make you feel scared, sad, or weird. You must share them with a trusted adult.”', 'Think about any bad secrets you’ve kept', 'Feel a little scared', 11, 12),
        (10, 'You quietly understand that telling someone is better than hiding.', 'Decide to talk to mom or teacher if needed', 'Ignore and stay silent', 13, 6),
        (11, 'You remember a time when an uncle made you uncomfortable. He said not to tell anyone.', 'Tell your mother immediately', 'Keep it to yourself', 14, 15),
        (12, 'Feeling scared is okay, but you now know you are not alone and you have rights.', 'Talk to a trusted adult', 'Stay confused and silent', 14, 6),
        (13, 'You decide to be brave and talk to a teacher you trust. She listens carefully and assures you it’s not your fault.', 'Feel supported', 'Still feel unsure', 16, 17),
        (14, 'Your mom listens carefully. She hugs you tightly and says you did the right thing. She takes action to protect you.', 'Feel proud and safe', None, 18, None),
        (15, 'Keeping it inside hurts you more. You feel anxious and scared. Please remember — you are never alone.', None, None, None, None),
        (16, 'The teacher informs the principal and your parents. The person is stopped and warned by authorities. You feel stronger and safe now.', 'Feel brave', None, 18, None),
        (17, 'You still feel unsure, but the teacher assures you it was brave of you to speak up.', 'Start to feel safe again', None, 18, None),
        (18, 'You now understand that your body belongs to **you**, and no one can touch you in a way that makes you uncomfortable. You are brave. 🏆', None, None, None, None)
    ]),
    ('Born to Shine ✨🌱', 'born_to_shine.jpg', [
        (1, 'You are a 9-year-old girl named Pari, living in a village. One day, you hear an elder saying, “Girls are a burden.”', 'Feel upset and confused', 'Ignore and walk away', 2, 3),
        (2, 'You feel a bit sad. At night, you ask your mom, “Was I unwanted?”', 'Wait for her answer', 'Cry silently', 4, 5),
        (3, 'You walk away, but something inside you feels strange. You wonder, "Why do people say that?"', 'Ask your teacher at school', 'Forget about it', 6, 7),
        (4, 'Your mom hugs you and says, “No beta, I fought for you to be born. You have the right to live, grow, and shine.”', 'Smile and hug her', 'Stay silent', 8, 9),
        (5, 'You cry alone. But the next day at school, your teacher teaches about *Right to Life and Birth*. You listen carefully.', 'Talk to her after class', 'Go home quietly', 6, 7),
        (6, 'Your teacher says: “Every child — boy or girl — has the right to be born, live safely, and get care and love.”', 'Feel proud to be a girl', 'Feel curious', 10, 10),
        (7, 'Forgetting about something important won’t help. Learning about your rights makes you stronger.', None, None, None, None),
        (8, 'Your mom says: “We all fought to protect your life. You’re a blessing, not a burden.” You feel brave.', 'Ask about other rights', 'Go to sleep peacefully', 10, 11),
        (9, 'Even in silence, you feel warm hearing her words. You now want to learn more.', 'Open your school book', 'Talk to your brother', 10, 12),
        (10, 'You learn about your rights:\n- Right to Food (Mid-Day Meals)\n- Right to Safe Water\n- Right to Free Health Checkups\n- Right to a Name and Nationality', 'Feel thankful', 'Ask more questions', 13, 14),
        (11, 'You sleep peacefully, but you also dream about a world where every girl is celebrated.', 'Draw about your dream', 'Write a poem in school', 15, 16),
        (12, 'Your brother says, “You’re smart and strong. You were born to do great things.” You smile.', 'Share with your friends', 'Keep it to yourself', 17, 16),
        (13, 'You tell your friends: “We get free food and vaccines because it’s our right, not charity.”', 'Everyone nods and smiles', None, 18, None),
        (14, 'You ask your teacher: “How do I get my birth certificate?” She explains the process to you kindly.', 'Tell your cousin to register too', 'Keep it to yourself', 19, 20),
        (15, 'You draw girls as superheroes, saving the world. Your teacher pins it on the wall. You feel proud.', None, None, None, None),
        (16, 'Your heart feels full. You were born, you are seen, and you will rise. You write: “I am not less. I am MORE.”', None, None, None, None),
        (17, 'Your friends get inspired. One girl says, “I will become a doctor!” The room fills with dreams.', None, None, None, None),
        (18, 'Children now speak proudly about their rights at school. You feel you’ve made a difference.', None, None, None, None),
        (19, 'Your cousin gets registered too. Now he can go to school and get vaccinations. He thanks you.', None, None, None, None),
        (20, 'You feel good knowing what you’ve learned, but remember: Rights grow stronger when shared.', None, None, None, None)
    ]),
    ('There is No Shame 💙', 'boy_supports_periods.jpg', [
        (1, 'You’re Aarav, a 13-year-old boy. Last week, your mom had a talk with you about puberty and periods. She said, “Boys must understand too. Periods are natural.”', 'You listened carefully', 'You felt awkward but stayed', 2, 2),
        (2, 'Today during the games period, your classmate Siya suddenly runs to the corner of the ground and sits behind a tree, crying.', 'Go check if she’s okay', 'Ignore and continue playing', 3, 4),
        (3, 'You walk slowly to her and ask, “Are you okay?” She covers her skirt and says softly, “Go away…” Her eyes are red.', 'Stay calm and kind', 'Say “What’s wrong?” again loudly', 5, 6),
        (4, 'You ignore her, but later you see some boys laughing and pointing at her. Something doesn’t feel right in your heart.', 'Decide to speak to a teacher', 'Still stay away', 7, 8),
        (5, 'You remember your mom’s words: “Sometimes when girls go through body changes, it can be overwhelming. If someone’s upset, don’t laugh — help.”', 'Run to the nearest female teacher', 'Ask your male coach to help', 9, 10),
        (6, 'She gets embarrassed and cries more. She says, “Just leave me alone!” You realize you should’ve been gentler.', None, None, None, None),
        (7, 'You walk up to the PE teacher and say, “Ma’am, I think Siya needs help. Please check.”', 'Wait nearby silently', 'Go back to class', 11, 11),
        (8, 'You walk away. Later, your teacher scolds everyone: “Some of you laughed at Siya. That’s shameful.” You feel guilty.', None, None, None, None),
        (9, 'The teacher rushes to Siya. You stand at a distance. She takes Siya inside gently and comforts her.', 'You smile quietly', 'You go sit back with your friends', 11, 12),
        (10, 'The coach says, “I don’t know… maybe call the nurse.” But you realize a female teacher would help more.', 'Run to get her instead', 'Let it be', 9, 8),
        (11, 'Later, the teacher finds you and says, “Thank you, Aarav. Most boys laugh or walk away. You helped.”', 'Say “Everyone should know this.”', 'Say “I just did what was right.”', 13, 13),
        (12, 'Your friends ask what happened. You say, “It’s her personal thing. Let her be. Don’t make fun.”', 'They nod respectfully', 'They laugh more', 13, None),
        (13, 'Your teacher arranges a short session: “Boys and girls must know about periods and body changes. It’s not shameful. It’s strength.”', 'You feel proud', 'You thank your mom silently', None, None)
    ]),
    ('Speak Up 💭', 'mental_health_support.jpg', [
        (1, 'You’re Atharva, a quiet 12-year-old boy. You’ve been feeling heavy inside for a long time. Your father shouts a lot at home. You don’t like going back there.', 'Tell no one. Just stay silent.', 'Speak to your class teacher privately', 2, 3),
        (2, 'You hide everything and pretend to be happy. But your marks drop, you stop laughing, and you always sit alone. People notice.', 'Say you’re just tired', 'Keep ignoring everyone', 4, 5),
        (3, 'You nervously tell your teacher, “Ma’am… I feel really scared sometimes… at home.” She looks at you gently and says, “You did the right thing.”', 'Look away and say nothing more', 'Open up a bit more', 6, 7),
        (4, 'Your friend Vaani says, “You’ve changed, Atharva. You can talk to me, you know?” You shrug and say, “I’m fine.”', 'Talk to her', 'Walk away quietly', 8, 5),
        (5, 'You keep it all inside. One day you suddenly start crying in class. The teacher takes you outside.', 'Stay silent again', 'Finally whisper “I need help”', 9, 9),
        (6, 'She gently says, “You are not alone, Atharva. No one should grow up scared. I’ll take you to the school counsellor.”', 'Say okay', 'Say “No! Don’t tell anyone.”', 10, 11),
        (7, 'You say, “Sometimes my dad throws things. He yells at my mom. I hate the noise.” The teacher listens calmly and says, “We will help you. You’re safe here.”', 'Cry softly', 'Nod in silence', 10, 10),
        (8, 'You tell Vaani everything. She doesn’t laugh. She listens. “You should talk to a grown-up,” she says. “This isn’t your fault.”', 'Agree to talk to teacher', 'Still hesitate', 3, 2),
        (9, 'The teacher contacts the school counsellor. You slowly start talking during sessions. You cry, draw, breathe. It’s hard… but you feel lighter.', 'Thank her after a few days', 'Just smile quietly', 12, 12),
        (10, 'The counsellor explains: “This is trauma, Atharva. It’s real. But there is help. Talking helps. Healing takes time, but it’s possible.”', 'Ask “Can I really get better?”', 'Stay quiet but hopeful', 12, 12),
        (11, 'The teacher says, “Okay. I won’t force you. But when you’re ready, I’ll be here.” That kindness sits in your heart.', 'Go back later on your own', 'Tell Vaani “She was nice”', 9, 8),
        (12, 'Weeks pass. You feel different. Safe. Stronger. You still have bad days, but now you talk. You draw. You don’t hide anymore.', 'Help other quiet kids now', 'Say “Healing is brave”', None, None)
    ]),
    ('School Bell Rings for Me Too 🔔', 'school_bell.jpg', [
        (1, 'You are 6 years old. You love singing and playing. But you don’t go to school like your neighbor Rani. One day, a volunteer visits your home.', 'Hide behind your mom', 'Run out to greet her', 2, 3),
        (2, 'The volunteer smiles and says, “Beta, would you like to go to school?” You peek from behind your mom.', 'Nod slowly', 'Say “No, I’m scared”', 4, 5),
        (3, 'The volunteer gives you a bright red pencil and says, “You have the right to learn, play, and grow!”', 'Smile and hold the pencil tight', 'Ask what "right" means', 4, 6),
        (4, 'Your mom says, “It’s free. You’ll get books, uniforms, and hot food too.” You get excited.', 'Say “Let’s go now!”', 'Ask if your friends are going', 7, 8),
        (5, 'You say no. The volunteer smiles and says, “That’s okay. Learning new things can be scary, but fun too.”', 'Think quietly', 'Shake your head again', 9, 10),
        (6, 'The volunteer says, “Right means something that belongs to *you*. Like your name or your voice — school is your right too.”', 'Feel curious', 'Stay silent', 4, 5),
        (7, 'You walk to school with your mom. You hear laughter and see children running to class.', 'Join them quickly', 'Hold your mom’s hand tightly', 11, 12),
        (8, 'Your best friend Chotu waves at you, “Come! We’re drawing butterflies today!”', 'Run to sit with him', 'Wait and observe', 11, 13),
        (9, 'Later that day, you watch Rani come home with a storybook and food. You feel a tiny wish in your heart.', 'Tell your mom you want to try', 'Stay quiet', 4, 10),
        (10, 'You miss another day of learning, laughing, and playing. But remember — the school gate is always open for you.', None, None, None, None),
        (11, 'In school, the teacher says, “Today, we’ll learn the alphabet AND play a fun clapping game!”', 'Get excited for both', 'Only want to play', 14, 15),
        (12, 'Your mom gives you a goodbye kiss. “Go be brave,” she says. You feel like a hero.', 'Smile wide and step in', 'Wave goodbye with a lump in your throat', 14, 16),
        (13, 'You sit quietly. A teacher kneels beside you and says, “Everyone has first-day jitters. Want to color a kite?”', 'Say yes shyly', 'Nod without speaking', 14, 14),
        (14, 'You start drawing and laughing. Then, you eat khichdi with your classmates. You feel warm and full.', 'Say “Thank you” loudly', 'Share your food with a friend', 17, 18),
        (15, 'The teacher smiles and says, “Play is learning too. But let’s balance both!” You nod.', 'Try the lesson with a smile', 'Only wait for the game', 17, 19),
        (16, 'You walk in bravely. A classmate smiles and says, “You can sit with me.” You feel less scared.', 'Sit beside them', 'Say “Hi” softly', 14, 14),
        (17, 'The teacher says, “This is your school. It’s free because it’s your **Right to Education**!”', 'Feel proud and important', 'Ask more questions', 20, 21),
        (18, 'Your friend smiles, “You’re kind!” You both make plans to play after school. This feels like home.', 'Laugh together', 'Plan a kite race', 22, 22),
        (19, 'You wait, but soon realize that games are more fun when you’ve learned something too.', 'Join the next class happily', None, 17, None),
        (20, 'You raise your hand and ask, “Can my little sister come too?” The teacher smiles, “Of course! She’ll go to Anganwadi!”', 'Tell your mom this', 'Run to hug your sister', 23, 24),
        (21, 'You learn about the RTE Act — from age 6 to 14, every child in India MUST be in school.', 'Feel safe and smart', None, 25, None),
        (22, 'You laugh and run with your friends. Every child should have this right — to play, eat, and dream.', None, None, None, None),
        (23, 'Your mom takes your 4-year-old sister to Anganwadi. She comes home singing rhymes and clapping.', 'Clap with her', 'Teach her new words', 25, 25),
        (24, 'You hug your sister and say, “Now you can learn too!” She smiles with wide eyes.', None, None, None, None),
        (25, 'You now know: school is not a luxury, it’s your RIGHT. You promise to tell every child this truth.', None, None, None, None)
    ]),
    ('She’s a Kid. Not a Bride 🚨', 'friend_marriage.jpg', [
        (1, 'You and your best friend Savi are in class 8. You laugh together, eat lunch together, and dream of becoming teachers one day.', 'Tell her your dream again', 'Ask her about her dream', 2, 3),
        (2, 'She smiles, “You’ll be the best teacher ever!” But she looks sad. Something is bothering her.', 'Ask what’s wrong', 'Stay quiet', 4, 5),
        (3, 'Savi says, “I wanted to be a nurse. But…” She stops. Her eyes look worried.', 'Ask her to tell you everything', 'Just nod silently', 4, 5),
        (4, 'Savi whispers, “My parents want me to get married next month. I’m only 14!” Your heart drops.', 'Feel angry and shocked', 'Hug her tightly', 6, 7),
        (5, 'The next day she doesn’t come to school. You hear rumors. Her engagement happened last night.', 'Go to her house', 'Talk to your teacher', 8, 9),
        (6, '“This is wrong!” you shout. Savi cries, “They say it’s for my safety.”', 'Tell her it’s illegal', 'Promise to stop it together', 10, 11),
        (7, 'You hug her. “You have rights,” you say. “We’ll fight this.” Savi nods with tears in her eyes.', 'Call Childline 1098', 'Go to school counselor', 12, 13),
        (8, 'You go to her house. Her mother says, “She can’t talk now. She’s going to be a bride soon.”', 'Sneak a note to her', 'Talk to her father bravely', 14, 15),
        (9, 'Your teacher says, “This is serious. Tell me everything.” You tell her about the child marriage.', 'Ask her for help', 'Say you’re scared', 13, 16),
        (10, 'You tell Savi, “The law says no girl can marry before 18. We’ll call 1098.”', 'Call from a shop phone', 'Use your school’s phone', 12, 13),
        (11, 'You both promise to stop it. But time is running out. Her engagement is in 3 days.', 'Rush to school for help', 'Look for police in the village', 13, 17),
        (12, 'You call Childline. They ask details gently: name, village, age. You answer bravely.', 'Tell them Savi’s full name', 'Tell them her father’s name', 18, 18),
        (13, 'With the help of your teacher and the Childline team, the officers arrive just in time.', 'Stay beside Savi', 'Hold her hand during questioning', 19, 19),
        (14, 'You pass her a small note: “You have rights. Don’t give up. I’m with you.”', 'Leave quietly', 'Wait for her reply', 15, 17),
        (15, 'You stand before her father. “Uncle, this marriage is illegal. It can ruin her life.” He stares in silence.', 'Run away after talking', 'Wait for his response', 17, 16),
        (16, 'You’re scared. But your teacher says, “Bravery is when you’re scared and still speak up.”', 'Take a deep breath', 'Nod and keep going', 13, 13),
        (17, 'You and Savi meet the officers. They explain that **child marriage is a crime under law**.', 'Listen carefully', 'Ask how to protect her', 19, 20),
        (18, 'The officers say, “Thank you. You just saved your friend’s childhood.” You feel powerful.', 'Smile proudly', 'Hold Savi’s hand', 21, 21),
        (19, 'The marriage is stopped. Savi’s father is warned. She hugs you and cries, “You saved my life.”', 'Hug her tight', 'Say “Now we’ll chase dreams”', 21, 21),
        (20, 'They explain the **Prohibition of Child Marriage Act, 2006**. Marrying before 18 is **illegal and dangerous**.', 'Feel proud to know this', 'Promise to help more girls', 21, 21),
        (21, 'You and Savi are back in school, smiling with books in hand. You now believe one voice *can* change the world.', 'Say “I’ll always stand for what’s right”', 'Say “I am proud of us”', None, None)
    ]),
    ('Not All Offers Are Safe 💬', 'protection_alert.jpg', [
        (1, 'You’re a 13-year-old girl who loves dancing. One day, you post a small video online. It gets many likes!', 'Feel excited', 'Feel nervous', 2, 2),
        (2, 'A man named “Raj Casting” messages you: “You dance well! Want to come for a Mumbai audition?”', 'Say “Thank you, I’ll ask my parents.”', 'Say “Wow! When should I come?”', 3, 4),
        (3, 'Your mom says, “No, this is risky. Why is he messaging a child online?” You feel confused.', 'Block the man', 'Message again secretly', 5, 6),
        (4, 'He asks for your age, phone number and says, “Don’t tell anyone. Real stars don’t wait.”', 'Feel proud and reply', 'Feel scared and delete', 6, 7),
        (5, 'You block him. Your mom reports the account. Later, you find out he’s been doing this to other girls too.', 'Feel brave', 'Spread awareness in class', 8, 9),
        (6, 'You reply “13”, and he says “Come alone. I’ll take care of tickets.” You feel weird, but also excited.', 'Go without telling anyone', 'Tell your best friend', 10, 11),
        (7, 'You delete it. But you feel confused and scared. Was it real or fake?', 'Ask your teacher about online safety', 'Forget it silently', 9, 12),
        (8, 'Your teacher gives a talk: “Any stranger offering you big things without adult involvement = red flag 🚨”', 'Take it seriously', 'Laugh it off', 13, 14),
        (9, 'In class, you speak: “Don’t reply to random DMs. Real opportunities never come secretly.”', 'Everyone listens', 'You feel proud', 13, 13),
        (10, 'You go alone. But at the station, you get scared. You don’t find anyone. You cry. A policewoman helps you.', 'She calls your parents', 'She explains this was trafficking', 15, 15),
        (11, 'Your friend tells the counselor. The counselor says, “You are very lucky to speak up. This is **exploitation**.”', 'Feel emotional', 'Say “What should I do now?”', 13, 13),
        (12, 'You say nothing. Days pass. The man vanishes. But you feel guilty and worried about others.', None, None, None, None),
        (13, 'You learn: **POCSO Act protects children from any kind of abuse. Even online messages count!**', 'Read more about it', 'Tell your younger cousin too', 16, 16),
        (14, 'You joke. But later, someone from your class gets trapped. You wish you took it seriously.', None, None, None, None),
        (15, 'You are rescued. Your parents cry and hug you. The officer says, “Never trust strangers online.”', 'Say “I’ve learnt my lesson”', 'Say “I want to help others now”', 16, 16),
        (16, 'From that day, you promise to speak up, stay aware, and protect others from being exploited.', 'Say “Safety is smart”', 'Say “Awareness saves lives”', None, None)
    ]),
    ('The Secret ? Not Anymore 🌸', 'menstrual_health.jpg', [
        (1, 'You’re in class 7. One day during class, you suddenly feel wet and uncomfortable. You look down. There’s a red stain on your skirt.', 'Panic and run to the washroom', 'Cover it with your bag and sit quietly', 2, 3),
        (2, 'You rush to the washroom, confused and scared. Your heart is racing. What is happening to you?', 'Cry alone', 'Call your best friend', 4, 5),
        (3, 'You try to hide it, but a few boys notice and giggle. Your face burns in embarrassment.', 'Run to the washroom now', 'Ignore and stay silent', 2, 6),
        (4, 'You cry quietly. You remember your mom once said something about “periods.” Is this that?', 'Check your underwear', 'Sit and wait alone', 7, 7),
        (5, 'Your best friend comes and holds your hand. “It’s okay,” she whispers. “You got your period. It’s normal.”', 'Ask “What do I do?”', 'Say “I feel gross”', 8, 8),
        (6, 'You sit silently, but feel shame and confusion. No one told you about this. Why is it a secret?', 'Talk to your female teacher', 'Go home silently after school', 9, 10),
        (7, 'Suddenly a senior girl walks in. She says softly, “Happened to me too. Wait, I have an extra pad.”', 'Thank her and wear the pad', 'Say “I don’t know how to use it”', 11, 12),
        (8, 'Your friend helps you wear a pad. She says, “Everyone goes through this. It’s nothing to feel dirty about.”', 'Smile with relief', 'Say “I want to learn more”', 13, 13),
        (9, 'Your teacher gently explains: “Periods are part of growing up. Don’t ever feel ashamed. You’re strong.”', 'Ask her more questions', 'Stay quiet but feel better', 13, 13),
        (10, 'You go home and cry. Your mom notices and hugs you. “You should’ve told me,” she says. “I’ll teach you.”', 'Open up to her', 'Just nod silently', 13, 13),
        (11, 'You say thanks and wear the pad. It feels strange but you’re glad you’re not alone.', 'Smile softly', 'Say “Why didn’t anyone prepare us?”', 13, 13),
        (12, 'She shows you how to wear it and says, “You should talk about this in class. We all deserve to know.”', 'Promise her you will', 'Feel unsure', 13, 13),
        (13, 'The next day, you and your teacher hold a small talk for girls. You say, “Let’s stop calling it shame. It’s strength.”', 'Girls clap for you', 'You feel proud and free', None, None)
    ]),
]

for title, image, steps in stories:
    c.execute('INSERT INTO stories (title, image) VALUES (?, ?)', (title, image))
    sid = c.lastrowid
    for step in steps:
        step_number, content, opt1, opt2, nxt1, nxt2 = step
        c.execute('''
            INSERT INTO steps (story_id, step_number, content, option1, option2, next1, next2)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (sid, step_number, content, opt1, opt2, nxt1, nxt2))

conn.commit()
conn.close()
print('stories.db created with existing and new romantic stories and images.')